<a href="https://colab.research.google.com/github/anvitha5456-creator/ML_LAB_2026-27/blob/main/pandas1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np
from statistics import mean, median, mode
list1 = [ 1, 2, 3, 4, 5]
array1 = np.array(list1)
print(array1)




[1 2 3 4 5]


In [26]:
print("Mean:", mean(list1))
print("Median:", median(list1))
print("Mode:", mode(list1))
print("Variance:", np.var(list1))
print("Standard Deviation:", np.std(list1))
list1.append(50)

print("Updated List:", list1)


Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951
Updated List: [1, 2, 3, 4, 5, 50]


In [21]:
import numpy as np
array1 = np.array([1,2,3,4])
print(array1)

[1 2 3 4]


In [27]:
print("Mean:", mean(list1))
print("Median:", median(list1))
print("Mode:", mode(list1))
print("Variance:", np.var(list1))
print("Standard Deviation:", np.std(list1))
list1.append(50)

print("Updated List:", list1)


Mean: 10.833333333333334
Median: 3.5
Mode: 1
Variance: 308.4722222222222
Standard Deviation: 17.563377301140637
Updated List: [1, 2, 3, 4, 5, 50, 50]



# create a 2D array with 2 rows and 4 columns

In [4]:
import numpy as np
array1 = np.array([[1,2,3,4],
                   [2,4,6,8]])
print(array1)

[[1 2 3 4]
 [2 4 6 8]]


In [23]:
print("Mean:", mean(list1))
print("Median:", median(list1))
print("Mode:", mode(list1))
print("Variance:", np.var(list1))
print("Standard Deviation:", np.std(list1))



Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951


Create a 3-D NumPy Array

In [24]:
import numpy as np
array1 = np.array([[[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]],

                [[13, 14, 15, 16],
                 [17, 18, 19, 20],
                 [21, 22, 23, 24]]])


print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [25]:
print("Mean:", mean(list1))
print("Median:", median(list1))
print("Mode:", mode(list1))
print("Variance:", np.var(list1))
print("Standard Deviation:", np.std(list1))


Mean: 3
Median: 3
Mode: 1
Variance: 2.0
Standard Deviation: 1.4142135623730951


check data type of num py array

In [28]:
array1 = np.array([10,45,67])
print(array1.dtype)

int64


check dimension of numpy array

In [29]:
print(array1.ndim)

1


check size of numpy array

In [31]:
print(array1.size)

3
